### PR TITLE
NavBar & Footer Component

### PR DESCRIPTION
**Pull request by WilliamMendez**
# Header
- Sticks to the top
- Has hover animations
- Lacks true navigation until new routes are created
image

# Footer
- Redirects to CS social networks (The linkedIn icon redirects to IEEE uniandes)
- Has hover animations
- TODO Newsletter functionality if we don't discard it
image

# Public folder
- Added svg files for icons

# Tailwind config
- Added mockup colors

# Index
- Removed astro svg that gets behind the header
- Added dupicated cards to test that the header sticks when scrolling

### CODE REVIEW

**Review by Crola1702 — APPROVED** [review]
LGTM.

Maybe we can add these to the main Layout?

**Comment by mr-sosa** [comment]
Some comments:
- [ ]  Review the footer in mobile view. 
- [ ] Menú Hamburger doesn't work well.
- [ ] Review the header in tablet view.

Finally, don't forget resolved the merge conflicts.

**Comment by WilliamMendez** [comment]
The preview for the fixes is the following:
- Mobile
mobile
- Tablet
mobile (1)
- Laptop
mobile (2)

**Review by mr-sosa — APPROVED** [review]
LGTM. 👌🏼

Now you could do the merge.

**Pull request merged**
